version: "3"

services:
  uci-api-db-gql:
    image: hasura/graphql-engine:v2.7.0
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgresql:${UCI_API_POSTGRES_PASSWORD}@${POSTGRES_HOST}:${UCI_API_DB_PORT}/${UCI_API_POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${UCI_API_DB_GRAPHQL_SECRET}
    ports:
      - "15003:8080"
    networks:
      uci-overlay:

networks:
  uci-overlay:
    external: true