yml
version: "3"

services:
  uci-admin:
    image: uci-admin
    build:
      context: uci-admin
      args:
        NG_APP_url: ${NG_APP_url}
        NG_APP_nl_url: ${NG_APP_nl_url}
        NG_APP_nl_login_url: ${NG_APP_nl_login_url}
        NG_APP_nl_login_token: ${NG_APP_nl_login_token}hist
        NG_APP_nl_application_id: ${NG_APP_nl_application_id}
        NG_APP_blobUrl: ${NG_APP_blobUrl}
        NG_APP_botPhoneNumber: ${NG_APP_botPhoneNumber}
        NG_APP_adapterId: ${NG_APP_adapterId}
        NG_APP_broadcastAdapterId: ${NG_APP_broadcastAdapterId}
        NG_APP_userId: ${NG_APP_userId}
        NG_APP_orgId: ${NG_APP_orgId}
        NG_APP_token: ${NG_APP_token}
    ports:
    - "9097:80"
    networks:
      uci-overlay:

networks:
  uci-overlay:
    external: true