version: "3"

services:
  transformer:
    image: "samagragovernance/transformer:${CURRENT_VERSION}"
    env_file: .env
    ports:
      - "${TRANSFORMER_INTERNAL_PORT}:${TRANSFORMER_INTERNAL_PORT}"
    networks:
      uci-overlay:

networks:
  uci-overlay:
    external: true